snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "ACCOUNTADMIN"
      database: "SAMPLE"
      warehouse: "COMPUTE_WH"
      schema: "SCHEMACHANGE"
      threads: 4
      client_session_keep_alive: False
