snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QAIFMDU-UV51997
      user: RAJ
      password: Rahul@3534928
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: "SAMPLE"
      schema: "SAMPLESCHEMA"
      threads: 4
      client_session_keep_alive: False
