snowflake:
  account: "UV51997"  # e.g., xy12345.us-east-1.aws
  user: "Raj"                  # e.g., CICD_USER
  role: "ACCOUNTADMIN"
  warehouse: "COMPUTE_WH"
  database: "SAMPLE"
  change_history_table: "SCHEMACHANGE.CHANGE_HISTORY"
  root_folder: "scripts/dev"
