name: Snowflake Schema Change
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install schemachange
      run: pip install schemachange==4.0.1
    - name: List repository contents
      run: ls -R
    - name: Show schemachange help
      run: schemachange deploy --help
    - name: Run schemachange
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        schemachange deploy \
          --root-folder "scripts/dev" \
          --snowflake-account "$SNOWFLAKE_ACCOUNT" \
          --snowflake-user "$SNOWFLAKE_USER" \
          --snowflake-role "ACCOUNYADMIN" \
          --snowflake-warehouse "COMPUTE_WH" \
          --snowflake-database "SAMPLE" \
          --change-history-table "SCHEMACHANGE.CHANGE_HISTORY" \
          --create-change-history-table \
          --snowflake-authenticator "password" \
          --dry-run
